[project]
name = "chili-iot"
version = "0.1.0"
description = "STM32 Bluepill sensor node"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "amqtt>=0.11.3",
    "black>=25.12.0",
    "mypy>=1.19.0",
    "pyserial>=3.5",
]
